
# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'windows-2019'
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- checkout: self 
  submodules: true

- template: common-dotnet.yml@templates
- template: common-win.yml@templates

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: KeraLua.sln

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: KeraLua.Core.sln

- task: PowerShell@2
  displayName: 'PreBuild Script'
  inputs:
    filePath: './devops/PreBuild.ps1'
    arguments: 'KeraLua KeraLua.nuspec'
    errorActionPreference: 'silentlyContinue'
    pwsh: true

- task: MSBuild@1
  displayName: 'Build solution KeraLua.sln'
  inputs:
    solution: KeraLua.sln
    configuration: Release

- task: MSBuild@1
  displayName: 'Build .NET Core'
  inputs:
    solution: KeraLua.Core.sln
    configuration: Release
    msbuildArguments: /restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet vstest'
  inputs:
    command: custom
    custom: vstest
    arguments: '.\tests\build\netcore\bin\Release\netcoreapp3.1\KeraLuaTest.Core.dll'

- task: MSBuild@1
  displayName: 'Build Android'
  inputs:
    solution: KeraLua.Android.sln
    configuration: Release
    msbuildArguments: '/p:AndroidNdkDirectory=%ANDROID_NDK_HOME%'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: '.\tests\build\net45\bin\Release\KeraLuaTest.dll'

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Xamarin.iOS'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Mac'
    specificBuildWithTriggering: true
    artifactName: Xamarin.iOS.KeraLua.dll

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Xamarin.Mac'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Mac'
    specificBuildWithTriggering: true
    artifactName: Xamarin.Mac.KeraLua.dll

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Xamarin.watchOS'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Mac'
    specificBuildWithTriggering: true
    artifactName: Xamarin.watchOS.KeraLua.dll

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Xamarin.tvOS'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Mac'
    specificBuildWithTriggering: true
    artifactName: Xamarin.tvOS.KeraLua.dll

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build liblua53.dylib'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Mac'
    specificBuildWithTriggering: true
    artifactName: liblua53.dylib

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build liblua53.so (Linux)'
  inputs:
    buildType: 'specific'
    project: 'NuGets'
    definition: 'KeraLua.Linux'
    specificBuildWithTriggering: true
    artifactName: liblua53.so

- task: CopyFiles@2
  displayName: 'Copy Files to: lib/Release/xamarinios/'
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\Xamarin.iOS.KeraLua.dll\'
    TargetFolder: lib/Release/xamarinios/

- task: CopyFiles@2
  displayName: 'Copy Files to: lib/Release/xamarinmac/'
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\Xamarin.Mac.KeraLua.dll\'
    TargetFolder: lib/Release/xamarinmac/

- task: CopyFiles@2
  displayName: 'Copy Files to: lib/Release/xamarintvos/ '
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\Xamarin.tvOS.KeraLua.dll\'
    TargetFolder: lib/Release/xamarintvos/

- task: CopyFiles@2
  displayName: 'Copy Files to: lib/Release/xamarinwatchos/'
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\Xamarin.watchOS.KeraLua.dll\'
    TargetFolder: lib/Release/xamarinwatchos/

- task: CopyFiles@2
  displayName: 'Copy Files to: runtimes/osx/native/'
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\liblua53.dylib\'
    TargetFolder: runtimes/osx/native/

- task: CopyFiles@2
  displayName: 'Copy Files to: runtimes/linux-x64/native/'
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)\liblua53.so\'
    TargetFolder: 'runtimes/linux-x64/native/'

- script: 'nuget setapikey $(apikey)'
  displayName: 'Set NuGet API Key'

- task: PowerShell@2
  displayName: 'Package NuGet'
  inputs:
    targetType: filePath
    filePath: ./devops/Package.ps1
    arguments: 'KeraLua KeraLua.nuspec'

- script: 'rename *.nupkg KeraLua.nupkg'
  displayName: 'Rename Nuget Package'

- task: PublishBuildArtifacts@1
  displayName: 'Save KeraLua.nupkg Artifact'
  inputs:
    PathtoPublish: KeraLua.nupkg
    ArtifactName: KeraLua.nupkg

- task: PowerShell@2
  displayName: 'Publish NuGet'
  inputs:
    targetType: filePath
    filePath: ./devops/Publish.ps1
    arguments: KeraLua

- template: send-telegram.yml@templates
