# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'ubuntu-16.04'
  demands: msbuild

steps:
- template: common-dotnet.yml@templates

- checkout: self 
  submodules: 'true'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: KeraLua.sln

- task: MSBuild@1
  displayName: 'Build solution KeraLua.sln'
  inputs:
    solution: KeraLua.sln
    configuration: Release

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: liblua53.so'
  inputs:
    PathtoPublish: 'runtimes/linux-x64/native/liblua53.so'
    ArtifactName: liblua53.so

- task: TriggerBuild@3
  displayName: 'Trigger a new build of KeraLua.Windows'
  inputs:
    buildDefinition: 'KeraLua.Windows'
    ignoreSslCertificateErrors: true
    useSameSourceVersion: true
    password: '$(myToken)'

- template: send-telegram.yml@templates